#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-common-annotations-api
Version  : 1.3.4
Release  : 1
URL      : https://github.com/eclipse-ee4j/common-annotations-api/archive/1.3.4-RELEASE.tar.gz
Source0  : https://github.com/eclipse-ee4j/common-annotations-api/archive/1.3.4-RELEASE.tar.gz
Source1  : https://repo1.maven.org/maven2/jakarta/annotation/jakarta.annotation-api/1.3.4/jakarta.annotation-api-1.3.4.jar
Source2  : https://repo1.maven.org/maven2/jakarta/annotation/jakarta.annotation-api/1.3.4/jakarta.annotation-api-1.3.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: mvn-common-annotations-api-data = %{version}-%{release}
Requires: mvn-common-annotations-api-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# Java(TM) Common Annotations
The intention of Java(TM) Common Annotations is to develop annotations for common semantic
concepts in the Java SE and Java EE platforms that apply across a variety of individual
technologies. It was envisioned that various JSRs would use annotations to enable a declarative
style of programming. It would be especially valuable to have consistency within the Java EE
component JSRs, but it is also valuable to allow consistency between Java EE and Java SE.

%package data
Summary: data components for the mvn-common-annotations-api package.
Group: Data

%description data
data components for the mvn-common-annotations-api package.


%package license
Summary: license components for the mvn-common-annotations-api package.
Group: Default

%description license
license components for the mvn-common-annotations-api package.


%prep
%setup -q -n common-annotations-api-1.3.4-RELEASE

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-common-annotations-api
cp LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-common-annotations-api/LICENSE.md
mkdir -p %{buildroot}/usr/share/java/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.4/jakarta.annotation-api-1.3.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.4/jakarta.annotation-api-1.3.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.4/jakarta.annotation-api-1.3.4.jar
/usr/share/java/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.4/jakarta.annotation-api-1.3.4.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-common-annotations-api/LICENSE.md
